alias mq="mvn -T3 clean install -Dpmd.skip -Dcheckstyle.skip -DskipAllTests -pl cortex-dce/cortex-dce-studio-webapp -am -Dmaven.test.skip=true"
alias mvnci="mvn clean install"
alias gl="git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s""
alias mci="mvn clean install -T3 -e"
alias mcis="mvn clean install -DskipAllTests"
alias src="source ~/.bash_profile"
alias rebasemaster="git rebase upstream/master"
alias gs="git status"
alias uploadtoaem="mvn clean install -P deploy-author"
